config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts

  devise_for :users

resources :posts do
  member do
    put "like", to: "posts#upvote"
    put "dislike", to: "posts#downvote"
  end
end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id =  current_user.id if current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to :back

    # current_user.voted_as_when_voted_for @comment1 # => true, he liked it
    # current_user.voted_as_when_voted_for @comment2 # => false, he didnt like it
    # current_user.voted_as_when_voted_for @comment3

  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to :back
  end
  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'partials/nav' %>
    <div class = "container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/partials/_nav.html.erb
<nav>
    <div class="nav-wrapper">
      <!-- <a href="#" class="brand-logo">Logo</a> -->
      <%= link_to "chowstagram", root_path, class: "brand-logo" %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>
<% if user_signed_in? %>
<li>
<%= link_to('Edit registration', edit_user_registration_path) %>
</li>
<% else %>
<li>
<%= link_to('Register', new_user_registration_path)  %>
</li>
<% end %>

      </ul>
    </div>
  </nav>

app/views/posts/_form.html.erb
<%= form_for post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <!-- <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div> -->
<div class = "field">
  <%= f.file_field :image %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

  <div class="row">
    <div class="col s12 m7 offset-s2">
      <% @posts.each do |post| %>
        <div class="card">

          <div class="card-image">
            <%= image_tag post.image, style: " height: auto;" %>
          </div>

          <div class="card-content">
            <p>
              <%= link_to "Image", post %><br>
              Submitted <%= time_ago_in_words(post.created_at) %>
              by <%= post.user.try(:email) %>
            </p>
            <strong>Description</strong><br>
              <%= post.description %> <br>
          </div>

          <div class="card-action">
              <p><%= post.get_upvotes.size %> likes
                <br>
                <!-- gets users who upvote -->
                <!-- "model"."action_array"."attribute"."for each" do |"function name|" -->
                <!-- "attribute"."value" -->
                <% post.get_upvotes.voters.each do |voter| %>
                <%= voter.email %>
                &nbsp
                <% end %>
              </p>
            </div>


          <div class="card-action">
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% if current_user %>
                <% if current_user.voted_up_on? post %>
                  <a>
                    <%= link_to dislike_post_path(post), method: :put do %>
                      <i class="fa fa-heart" aria-hidden="true"></i>
                    <% end %>
                  </a>
                <% else %>
                  <a>
                    <%= link_to like_post_path(post), method: :put do %>
                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                    <% end %>
                  </a>
                <% end %>
                <% else %>
                  <p>
                    Please sign in
                  </p>
            <% end %>

            </div>
          <!-- <div class="card-action">
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>

            <%= link_to like_post_path(post), method: :put do %>
                <i class="fa fa-heart" aria-hidden="true"></i>
                <%= post.get_upvotes.size %>
            <% end %> -->

            <!-- <%= link_to dislike_post_path(post), method: :put do %>
                  Downvote
                  <%= post.get_downvotes.size %>
            <% end %> -->

        </div>
        <% end %>
      </div>
    </div>


<%= link_to 'New Post', new_post_path %>
<!-- <% @posts.each do |post| %>
    <p>
      <%= link_to post.image, post %><br>
      Submitted <%= time_ago_in_words(post.created_at) %>
      by <%= post.user.try(:email) %>
    </p> -->

    <!-- <%= link_to like_post_path(post), method: :put do %>
  Upvote
  <%= post.get_upvotes.size %>
<% end %>

<%= link_to dislike_post_path(post), method: :put do %>
  Downvote
  <%= post.get_downvotes.size %>
<% end %> -->
<!-- <% end %> -->

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>
<!-- i just added , post: @post -->
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>

<p>
  <%= image_tag @post.image %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>